attempt to maintain furthest position byte channel has reached
joshbooks/JoshDB pull request #2
Opened 2019-04-30 03:44 UTC by malbx

@joshbooks Let me know if this is what you had in mind for the TODO addressed by this PR.

2019-04-30 04:57 UTC, joshbooks commented
It is exactly what I had in mind but I was wrong, looks like the contention on the AtomicLong is a bigger deal than I thought.
before: 
It took 51759670 nanoseconds to read 32 objects, each 65536 bytes long
It took 48412782 nanoseconds to read 32 objects, each 65536 bytes long
It took 42621039 nanoseconds to read 32 objects, each 65536 bytes long
It took 52777367 nanoseconds to read 32 objects, each 65536 bytes long
after: 
It took 56631026 nanoseconds to read 32 objects, each 65536 bytes long
It took 54522207 nanoseconds to read 32 objects, each 65536 bytes long
It took 60950088 nanoseconds to read 32 objects, each 65536 bytes long
It took 66747348 nanoseconds to read 32 objects, each 65536 bytes long
Will add a suggestion in a moment.

2019-04-30 05:02 UTC, joshbooks commented
Ok, afer appying the change I'm about to suggest we get:
It took 42028089 nanoseconds to read 32 objects, each 65536 bytes long
It took 45712212 nanoseconds to read 32 objects, each 65536 bytes long
It took 46162561 nanoseconds to read 32 objects, each 65536 bytes long
It took 41785378 nanoseconds to read 32 objects, each 65536 bytes long

2019-04-30 05:07 UTC, joshbooks requested changes

2019-04-30 05:07 UTC, joshbooks commented on main/src/org/josh/JoshDB/FileTrie/MergeFile.java
> +  private final AtomicLong byteChannelPosition = new AtomicLong(0);
```suggestion
  private final Counter byteChannelPosition = new Counter();
```

2019-04-30 05:07 UTC, joshbooks commented on main/src/org/josh/JoshDB/FileTrie/MergeFile.java
> +      channel.position(byteChannelPosition.get());
```suggestion
      channel.position(byteChannelPosition.estimate_get());
```

2019-04-30 05:07 UTC, joshbooks commented on main/src/org/josh/JoshDB/FileTrie/MergeFile.java
>        addPageInfo(buffer, pageOffset);
```suggestion
      if(addPageInfo(buffer, pageOffset))
      {
        byteChannelPosition.add(PIPE_BUF);
      }
```

2019-04-30 05:07 UTC, joshbooks commented on main/src/org/josh/JoshDB/FileTrie/MergeFile.java
> +      byteChannelPosition.accumulateAndGet(fileStream.position(), Math::max);
```suggestion
```

2019-05-02 04:12 UTC, malbx commented
I addressed the issues that were pointed out.  Let me know if you notice anything else.

2019-05-02 18:23 UTC, joshbooks approved these changes

2019-05-02 18:45 UTC, merged